# Site settings
author: Noah Scala
title: Noah Scala's Coding Blog
header-img: img/home-bg.png
email: tobi8912@gmail.com
copyright_name: Noah Scala
description: > # this means to ignore newlines until "baseurl:"
  A blog by Noah Scala about coding and learning to do so
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nwscala

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
